AWSTemplateFormatVersion: '2010-09-09'
Description: 'code commit repository'

Parameters:

  Name:
    Type: String
    Default: Bob
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
    MinLength: 1
    MaxLength: 100
    Description: Project name, used in CodeCommit repository name, must be
      unique across region

  Description:
    Type: String
    Default: ""
    MinLength: 0
    MaxLength: 100
    Description: Project description

Resources:
  Repository:
    Type: "AWS::CodeCommit::Repository"
    Properties:
      RepositoryName: !Ref Name
      RepositoryDescription: !Ref Description

Outputs:
  RepositoryName:
    Description: Name of the git repository.
    Value: !Ref Repository
  RepositoryArn:
    Description: ARN of the git repository.
    Value: !GetAtt Repository.Arn
  GitCloneUrlHttp:
    Description: The URL to use for cloning the repository over HTTPS.
    Value: !GetAtt Repository.CloneUrlHttp
  GitCloneUrlSsh:
    Description: The URL to use for cloning the repository over SSH.
    Value: !GetAtt Repository.CloneUrlSsh
