AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  NotExpireCondition: !Equals [!Ref 'RetentionDays', -1]
Description: VPC flow logging
Outputs:
  FlowLog:
    Description: Flow log ID
    Value: !Ref 'FlowLog'
  LogGroupArn:
    Description: Arn of the log group.
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupArn'
    Value: !GetAtt 'LogGroup.Arn'
  LogGroupName:
    Description: Name of the log group.
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'
    Value: !Ref 'LogGroup'
Parameters:
  ResourceId:
    Description: The ID of the subnet, network interface, or VPC for which you want
      to create a flow log.
    Type: String
  ResourceType:
    AllowedValues:
    - VPC
    - Subnet
    - NetworkInterface
    Default: VPC
    Description: The type of resource that you specified in the ResourceId parameter
    Type: String
  RetentionDays:
    AllowedValues:
    - -1
    - 1
    - 3
    - 5
    - 7
    - 14
    - 30
    - 60
    - 90
    - 120
    - 150
    - 180
    - 365
    - 400
    - 545
    - 731
    - 1827
    - 3653
    Default: '-1'
    Description: The number of days log events are kept in CloudWatch Logs.
    Type: Number
  TrafficType:
    AllowedValues:
    - ACCEPT
    - REJECT
    - ALL
    Default: ALL
    Description: The type of traffic to log.
    Type: String
Resources:
  FlowLog:
    Properties:
      DeliverLogsPermissionArn: !GetAtt 'LogDeliveryRole.Arn'
      LogGroupName: !Ref 'LogGroup'
      ResourceId: !Ref 'ResourceId'
      ResourceType: !Ref 'ResourceType'
      TrafficType: !Ref 'TrafficType'
    Type: AWS::EC2::FlowLog
  LogDeliveryRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - vpc-flow-logs.amazonaws.com
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
            - !GetAtt 'LogGroup.Arn'
          Version: '2012-10-17'
        PolicyName: AllowReadSrcBucket
    Type: AWS::IAM::Role
  LogGroup:
    Properties:
      RetentionInDays: !If [NotExpireCondition, !Ref 'AWS::NoValue', !Ref 'RetentionDays']
    Type: AWS::Logs::LogGroup
