version: 0.2

env:
  variables:
    CFN_TEMPLATE_DIR: "./solutions"
    CFN_MASTER_TEMPLATE: Main.template.yaml
    CFN_PROD_CONFIG: "config.prod.json"
    CFN_TEST_CONFIG: "config.test.json"

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo "Start validating and packaging templates..."
  build:
    commands:
      - WORKDIR=`pwd`
      - mkdir -p /tmp/dist
      - cp $CFN_TEST_CONFIG /tmp/dist/config.test.json
      - cp $CFN_PROD_CONFIG /tmp/dist/config.prod.json
      - cd $CFN_TEMPLATE_DIR && echo `pwd`
      - PACKAGED_MASTER_TEMPLATE=`mktemp`
      - aws cloudformation package --template-file $CFN_MASTER_TEMPLATE --s3-bucket $CFN_PACKAGE_BUCKET --s3-prefix packaged/ --output-template-file $PACKAGED_MASTER_TEMPLATE
      - cp $PACKAGED_MASTER_TEMPLATE /tmp/dist/Packaged.Master.template

  post_build:
    commands:
      - echo "Done."

artifacts:
  files:
    - Packaged.Master.template
    - config.test.json
    - config.prod.json
  base-directory: /tmp/dist
  discard-paths: yes