AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora for Postgres cluster.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VpcId
          - SubnetIds
          - SecurityGroup
      - Label:
          default: Database Basic Configuration
        Parameters:
          - DatabaseClass
          - DatabaseEngine
          - DatabaseReadReplicas
          - DatabaseUser
          - DatabasePassword
      - Label:
          default: Database Storage Configuration
        Parameters:
          - StorageType
          - StorageIops
          - StorageEncrypted
          - KmsKeyId
      - Label:
          default: Database Security Configuration
        Parameters:
          - EnhancedMonitoringConditionRole
          - ClientLocation
          - PubliclyAccessible
    ParameterLabels:
      ClientLocation:
        default: Client Location
      DatabaseClass:
        default: Database Class
      DatabaseEngine:
        default: Database Engine
      DatabasePassword:
        default: Database Password
      DatabaseReadReplicas:
        default: Database Read Replicas
      DatabaseUser:
        default: Database User
      EnhancedMonitoringConditionRole:
        default: Enhanced Monitoring Condition Role
      KmsKeyId:
        default: Kms Key Id
      PubliclyAccessible:
        default: Publicly Accessible
      SecurityGroup:
        default: Security Group
      StorageEncrypted:
        default: Storage Encrypted
      StorageIops:
        default: Storage Iops
      StorageType:
        default: Storage Type
      SubnetIds:
        default: Subnet Ids
      VpcId:
        default: Vpc Id
Parameters:
  ClientLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
    Default: '0.0.0.0/0'
    Description: Lockdown database access (default can be accessed from anywhere)
    MaxLength: '18'
    MinLength: '9'
    Type: String
  DatabaseClass:
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.m3.medium
      - db.m3.large
      - db.m3.xlarge
      - db.m3.2xlarge
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
    Default: db.r3.large
    Description: Database instance class
    Type: String
  DatabaseEngine:
    AllowedValues:
      - aurora
      - aurora-mysql
      - aurora-postgresql
    Default: postgres
    Description: Database engine
    Type: String
  DatabasePassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: The database admin account password, ignored when a snapshot is specified
    MaxLength: '41'
    MinLength: '1'
    NoEcho: true
    Type: String
  DatabaseReadReplicas:
    Default: 0
    Description: Number of read replica instances, set to 0 disables read replicas.
    MaxValue: 16
    MinValue: 0
    Type: Number
  DatabaseSnapshot:
    Default: ''
    Description: ARN of a DB snapshot to restore from
    Type: String
  DatabaseUser:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Description: The database admin account username, ignored when a snapshot is specified
    MaxLength: '16'
    MinLength: '1'
    NoEcho: true
    Type: String
  EnhancedMonitoringConditionRole:
    AllowedValues:
      - ''
      - rds-monitoring-role
    Default: ''
    Description: Database enhanced monitoring role name, leaf blank to disable enhanced
      monitoring
    Type: String
  KmsKeyId:
    Default: ''
    Description: The ARN of the KMS master key that is used to encrypt the DB instance,
      If you enable the StorageEncrypted property but don't specify this property,
      AWS CloudFormation uses the default master key.
    Type: String
  PubliclyAccessible:
    AllowedValues:
      - 'false'
      - 'true'
    Default: 'false'
    Description: Whether the database endpoint is publicly accessible
    Type: String
  SecurityGroup:
    Default: ''
    Description: Database security group id, a new security group will be created
      this is left empty.
    Type: String
  StorageEncrypted:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Indicates whether the DB instance is encrypted.
    Type: String
  StorageIops:
    ConstraintDescription: IOPS range is 100 to 30000
    Default: '100'
    Description: IOPS database storage supports, used when the volume type is io1
    MaxValue: '30000'
    MinValue: '100'
    Type: Number
  StorageSize:
    ConstraintDescription: must be between 5GB and 6TB.
    Default: '5'
    Description: The size of the database storage in GB
    MaxValue: '6144'
    MinValue: '5'
    Type: Number
  StorageType:
    AllowedValues:
      - gp2
      - io1
      - default
    Default: gp2
    Description: Database storage type
    Type: String
  SubnetIds:
    Description: SubnetIds of existing subnets of the VPC
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Description: VpcId of an existing VPC.
    Type: AWS::EC2::VPC::Id
Resources:
  DatabaseSubnetGroup:
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds: !Ref 'SubnetIds'
    Type: AWS::RDS::DBSubnetGroup
  RdsCluster:
    DeletionPolicy: Delete
    Properties:
      DBSubnetGroupName: !Ref 'DatabaseSubnetGroup'
      Engine: !Ref 'DatabaseEngine'
      KmsKeyId: !If
        - StorageEncryptedConditon
        - !If
          - DefaultKmsCondition
          - !Ref 'AWS::NoValue'
          - !Ref 'KmsKeyId'
        - !Ref 'AWS::NoValue'
      MasterUserPassword: !If
        - NewDatabaseCondition
        - !Ref 'DatabasePassword'
        - !Ref 'AWS::NoValue'
      MasterUsername: !If
        - NewDatabaseCondition
        - !Ref 'DatabaseUser'
        - !Ref 'AWS::NoValue'
      Port: '3306'
      StorageEncrypted: !Ref 'StorageEncrypted'
      VpcSecurityGroupIds:
        - !If
          - CreateSecurityGroupCondition
          - !Ref 'RdsSecurityGroup'
          - !Ref 'SecurityGroup'
    Type: AWS::RDS::DBCluster
  RdsInstance1:
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref 'RdsCluster'
      DBInstanceClass: !Ref 'DatabaseClass'
      Engine: !Ref 'DatabaseEngine'
      MonitoringInterval: !If
        - EnhancedMonitoringCondition
        - '60'
        - !Ref 'AWS::NoValue'
      MonitoringRoleArn: !If
        - EnhancedMonitoringCondition
        - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EnhancedMonitoringConditionRole}'
        - !Ref 'AWS::NoValue'
      PubliclyAccessible: !Ref 'PubliclyAccessible'
    Type: AWS::RDS::DBInstance
  RdsInstance2:
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref 'RdsCluster'
      DBInstanceClass: !Ref 'DatabaseClass'
      Engine: aurora
      MonitoringInterval: !If
        - EnhancedMonitoringCondition
        - '60'
        - !Ref 'AWS::NoValue'
      MonitoringRoleArn: !If
        - EnhancedMonitoringCondition
        - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EnhancedMonitoringConditionRole}'
        - !Ref 'AWS::NoValue'
      PubliclyAccessible: !Ref 'PubliclyAccessible'
    Type: AWS::RDS::DBInstance
  RdsSecurityGroup:
    Condition: CreateSecurityGroupCondition
    Properties:
      GroupDescription: Enable local postgres access
      SecurityGroupIngress:
        - !If
          - PostgresCondition
          - CidrIp: !Ref 'ClientLocation'
            FromPort: '5432'
            IpProtocol: tcp
            ToPort: '5432'
          - !Ref 'AWS::NoValue'
        - !If
          - MysqlCondition
          - CidrIp: !Ref 'ClientLocation'
            FromPort: '3306'
            IpProtocol: tcp
            ToPort: '3306'
          - !Ref 'AWS::NoValue'
      VpcId: !Ref 'VpcId'
    Type: AWS::EC2::SecurityGroup
