AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  ChinaRegionCondition: !Equals [!Ref 'AWS::Region', cn-north-1]
  CreateSecurityGroupCondition: !Equals [!Ref 'SecurityGroup', '']
  DefaultKmsCondition: !Equals [!Ref 'KmsKeyId', '']
  EnhancedMonitoringCondition: !Equals [!Ref 'DatabaseEnhancedMonitoring', 'true']
  IopsStorageCondition: !Equals [!Ref 'StorageType', io1]
  NewDatabaseCondition: !Equals [!Ref 'DatabaseSnapshot', '']
  OneDatabaseReadReplicaCondition: !Or [!Equals [!Ref 'DatabaseReadReplicas', '1'],
    !Equals [!Ref 'DatabaseReadReplicas', '2']]
  StorageEncryptedConditon: !Equals [!Ref 'StorageEncrypted', 'true']
  TwoDatabaseReadReplicaCondition: !Equals [!Ref 'DatabaseReadReplicas', '2']
  UseSnapshotCondition: !Not [!Equals [!Ref 'DatabaseSnapshot', '']]
Description: PostgreSQL RDS instance.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VpcId
      - SubnetIds
      - SecurityGroup
    - Label:
        default: Database Basic Configuration
      Parameters:
      - DatabaseSnapshot
      - DatabaseClass
      - DatabaseEngineVersion
      - DatabaseMultiAz
      - DatabaseUser
      - DatabasePassword
      - DatabaseEnhancedMonitoring
    - Label:
        default: Database Storage Configuration
      Parameters:
      - StorageSize
      - StorageType
      - StorageIops
      - StorageEncrypted
      - KmsKeyId
    - Label:
        default: Database Security Configuration
      Parameters:
      - ClientLocation
      - PubliclyAccessible
    - Label:
        default: Database Replication Configuration
      Parameters:
      - DatabaseReplication
    ParameterLabels:
      ClientLocation:
        default: Client Location
      DatabaseClass:
        default: Database Class
      DatabaseEngineVersion:
        default: Database Engine Version
      DatabaseEnhancedMonitoring:
        default: Database Enhanced Monitoring
      DatabaseMultiAz:
        default: Database Multi Az
      DatabasePassword:
        default: Database Password
      DatabaseReplication:
        default: Database Replication
      DatabaseSnapshot:
        default: Database Snapshot
      DatabaseUser:
        default: Database User
      KmsKeyId:
        default: Kms Key Id
      PubliclyAccessible:
        default: Publicly Accessible
      SecurityGroup:
        default: Security Group
      StorageEncrypted:
        default: Storage Encrypted
      StorageIops:
        default: Storage Iops
      StorageSize:
        default: Storage Size
      StorageType:
        default: Storage Type
      SubnetIds:
        default: Subnet Ids
      VpcId:
        default: Vpc Id
Outputs:
  EndpointAddress:
    Description: Endpoint address
    Value: !GetAtt 'RdsInstance.Endpoint.Address'
  EndpointPort:
    Description: Endpoint port
    Value: !GetAtt 'RdsInstance.Endpoint.Port'
  EnvironmentVariables:
    Description: Database environment variables
    Value: !Sub 'PGHOST=${RdsInstance.Endpoint.Address} PGPORT=${RdsInstance.Endpoint.Port}
      PGUSER=${DatabaseUser} PGPASSWORD=${DatabasePassword} '
Parameters:
  ClientLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: Lockdown database access (default can be accessed from anywhere)
    MaxLength: '18'
    MinLength: '9'
    Type: String
  DatabaseClass:
    AllowedValues:
    - db.t2.micro
    - db.t2.small
    - db.t2.medium
    - db.t2.large
    - db.m3.medium
    - db.m3.large
    - db.m3.xlarge
    - db.m3.2xlarge
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m4.4xlarge
    - db.m4.10xlarge
    - db.m4.16xlarge
    - db.r3.large
    - db.r3.xlarge
    - db.r3.2xlarge
    - db.r3.4xlarge
    - db.r3.8xlarge
    Default: db.t2.micro
    Description: Database instance class
    Type: String
  DatabaseEngineVersion:
    AllowedValues:
    - 9.6.3
    - 9.6.2
    - 9.6.1
    - 9.5.7
    - 9.5.6
    - 9.5.4
    - 9.5.2
    - 9.4.12
    - 9.4.11
    - 9.4.9
    - 9.4.7
    - 9.3.17
    - 9.3.16
    - 9.3.14
    - 9.3.12
    Default: 9.6.3
    Description: Database engine version
    Type: String
  DatabaseEnhancedMonitoring:
    AllowedValues:
    - 'false'
    - 'true'
    Default: 'false'
    Description: Whether enables database enhanced monitoring
    Type: String
  DatabaseMultiAz:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Description: Whether use a multi-AZ Deployment
    Type: String
  DatabasePassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: The database admin account password, ignored when a snapshot is specified
    MaxLength: '41'
    MinLength: '1'
    NoEcho: true
    Type: String
  DatabaseReadReplicas:
    AllowedValues:
    - '0'
    - '1'
    - '2'
    Default: '0'
    Description: Number of read replicas of the master database.
    Type: String
  DatabaseSnapshot:
    Default: ''
    Description: ARN of a DB snapshot to restore from
    Type: String
  DatabaseUser:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Description: The database admin account username, ignored when a snapshot is specified
    MaxLength: '16'
    MinLength: '1'
    NoEcho: true
    Type: String
  KmsKeyId:
    Default: ''
    Description: The ARN of the KMS master key that is used to encrypt the DB instance,
      If you enable the StorageEncrypted property but don't specify this property,
      this template uses the default master key.
    Type: String
  PubliclyAccessible:
    AllowedValues:
    - 'false'
    - 'true'
    Default: 'false'
    Description: Whether the database endpoint is publicly accessible
    Type: String
  SecurityGroup:
    Default: ''
    Description: Database security group id, a new security group will be created
      this is left empty.
    Type: String
  StorageEncrypted:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Description: Indicates whether the DB instance is encrypted.
    Type: String
  StorageIops:
    ConstraintDescription: IOPS range is 100 to 30000
    Default: '100'
    Description: IOPS capability of the database storage, only used when the volume
      type is io1
    MaxValue: '30000'
    MinValue: '100'
    Type: Number
  StorageSize:
    ConstraintDescription: must be between 5GB and 6TB.
    Default: '5'
    Description: The size of the database storage in GB
    MaxValue: '6144'
    MinValue: '5'
    Type: Number
  StorageType:
    AllowedValues:
    - gp2
    - io1
    - default
    Default: gp2
    Description: Database storage type
    Type: String
  SubnetIds:
    Description: SubnetIds of existing subnets of the VPC
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Description: VpcId of an existing VPC.
    Type: AWS::EC2::VPC::Id
Resources:
  DatabaseSubnetGroup:
    Properties:
      DBSubnetGroupDescription: Postgres RDS subnet group
      SubnetIds: !Ref 'SubnetIds'
    Type: AWS::RDS::DBSubnetGroup
  EnhancedMonitoringRole:
    Condition: EnhancedMonitoringCondition
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - !If [ChinaRegionCondition, monitoring.rds.amazonaws.com.cn, monitoring.rds.amazonaws.com]
      ManagedPolicyArns:
      - !Sub ['arn:${PARTITION}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole',
        {PARTITION: !If [ChinaRegionCondition, aws-cn, aws]}]
    Type: AWS::IAM::Role
  RdsInstance:
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: !Ref 'StorageSize'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: !Ref 'DatabaseClass'
      DBSnapshotIdentifier: !If [UseSnapshotCondition, !Ref 'DatabaseSnapshot', !Ref 'AWS::NoValue']
      DBSubnetGroupName: !Ref 'DatabaseSubnetGroup'
      Engine: postgres
      EngineVersion: !Ref 'DatabaseEngineVersion'
      Iops: !If [IopsStorageCondition, !Ref 'StorageIops', !Ref 'AWS::NoValue']
      KmsKeyId: !If [StorageEncryptedConditon, !If [DefaultKmsCondition, !Ref 'AWS::NoValue',
          !Ref 'KmsKeyId'], !Ref 'AWS::NoValue']
      MasterUserPassword: !If [NewDatabaseCondition, !Ref 'DatabasePassword', !Ref 'AWS::NoValue']
      MasterUsername: !If [NewDatabaseCondition, !Ref 'DatabaseUser', !Ref 'AWS::NoValue']
      MonitoringInterval: !If [EnhancedMonitoringCondition, '60', !Ref 'AWS::NoValue']
      MonitoringRoleArn: !If [EnhancedMonitoringCondition, !GetAtt 'EnhancedMonitoringRole.Arn',
        !Ref 'AWS::NoValue']
      MultiAZ: !Ref 'DatabaseMultiAz'
      Port: '5432'
      PubliclyAccessible: !Ref 'PubliclyAccessible'
      StorageEncrypted: !Ref 'StorageEncrypted'
      StorageType: !Ref 'StorageType'
      VPCSecurityGroups:
      - !If [CreateSecurityGroupCondition, !Ref 'RdsSecurityGroup', !Ref 'SecurityGroup']
    Type: AWS::RDS::DBInstance
  RdsReadReplicaInstance1:
    Condition: OneDatabaseReadReplicaCondition
    DependsOn: RdsInstance
    Properties:
      AllocatedStorage: !Ref 'StorageSize'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: !Ref 'DatabaseClass'
      Engine: postgres
      EngineVersion: !Ref 'DatabaseEngineVersion'
      Iops: !If [IopsStorageCondition, !Ref 'StorageIops', !Ref 'AWS::NoValue']
      KmsKeyId: !If [StorageEncryptedConditon, !If [DefaultKmsCondition, !Ref 'AWS::NoValue',
          !Ref 'KmsKeyId'], !Ref 'AWS::NoValue']
      MonitoringInterval: !If [EnhancedMonitoringCondition, '60', !Ref 'AWS::NoValue']
      MonitoringRoleArn: !If [EnhancedMonitoringCondition, !GetAtt 'EnhancedMonitoringRole.Arn',
        !Ref 'AWS::NoValue']
      Port: '5432'
      PubliclyAccessible: !Ref 'PubliclyAccessible'
      SourceDBInstanceIdentifier: !Ref 'RdsInstance'
      StorageEncrypted: !Ref 'StorageEncrypted'
      StorageType: !Ref 'StorageType'
      VPCSecurityGroups:
      - !If [CreateSecurityGroupCondition, !Ref 'RdsSecurityGroup', !Ref 'SecurityGroup']
    Type: AWS::RDS::DBInstance
  RdsReadReplicaInstance2:
    Condition: TwoDatabaseReadReplicaCondition
    DependsOn: RdsInstance
    Properties:
      AllocatedStorage: !Ref 'StorageSize'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: !Ref 'DatabaseClass'
      Engine: postgres
      EngineVersion: !Ref 'DatabaseEngineVersion'
      Iops: !If [IopsStorageCondition, !Ref 'StorageIops', !Ref 'AWS::NoValue']
      KmsKeyId: !If [StorageEncryptedConditon, !If [DefaultKmsCondition, !Ref 'AWS::NoValue',
          !Ref 'KmsKeyId'], !Ref 'AWS::NoValue']
      MonitoringInterval: !If [EnhancedMonitoringCondition, '60', !Ref 'AWS::NoValue']
      MonitoringRoleArn: !If [EnhancedMonitoringCondition, !GetAtt 'EnhancedMonitoringRole.Arn',
        !Ref 'AWS::NoValue']
      Port: '5432'
      PubliclyAccessible: !Ref 'PubliclyAccessible'
      SourceDBInstanceIdentifier: !Ref 'RdsInstance'
      StorageEncrypted: !Ref 'StorageEncrypted'
      StorageType: !Ref 'StorageType'
      VPCSecurityGroups:
      - !If [CreateSecurityGroupCondition, !Ref 'RdsSecurityGroup', !Ref 'SecurityGroup']
    Type: AWS::RDS::DBInstance
  RdsSecurityGroup:
    Condition: CreateSecurityGroupCondition
    Properties:
      GroupDescription: Enable local postgres access
      SecurityGroupIngress:
      - CidrIp: !Ref 'ClientLocation'
        FromPort: '5432'
        IpProtocol: tcp
        ToPort: '5432'
      VpcId: !Ref 'VpcId'
    Type: AWS::EC2::SecurityGroup
