AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 origin content bucket
Outputs:
  BucketArn:
    Description: Amazon Resource Name the bucket
    Value: !GetAtt 'Bucket.Arn'
  BucketName:
    Description: Bucket name
    Value: !Ref 'Bucket'
  DomainName:
    Description: IPv4 DNS name of the bucket
    Value: !GetAtt 'Bucket.DomainName'
Parameters:
  OriginAccessIdentity:
    AllowedPattern: '[A-Z0-9]+'
    ConstraintDescription: must be a valid OAI name
    Description: Id of the Cloudfront Origin Access Identity
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  BucketPolicy:
    DependsOn: Bucket
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument:
        Id: CdnAccessPolicy
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
              ${OriginAccessIdentity}'
          Resource: !Sub '${Bucket.Arn}/*'
          Sid: '1'
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
