AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  ChinaRegionCondition: !Equals [!Ref 'AWS::Region', cn-north-1]
  HasBucketName: !Not [!Equals [!Ref 'BucketName', '']]
Description: CloudWatch Logs S3 export bucket
Outputs:
  BucketName:
    Description: S3 bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
    Value: !Ref 'Bucket'
Parameters:
  BucketName:
    AllowedPattern: '[-\.a-z0-9]*'
    Default: ''
    Description: Bucket name
    Type: String
  IaInDays:
    Default: 30
    Description: Days before translating current object.
    MaxValue: 3650
    MinValue: 30
    Type: Number
  RetireInDays:
    Default: 3650
    Description: Days before retire current object, set to 0 disables retirement
    MaxValue: 3650
    MinValue: 90
    Type: Number
Resources:
  Bucket:
    Properties:
      BucketName: !If [HasBucketName, !Ref 'BucketName', !Ref 'AWS::NoValue']
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: !Ref 'RetireInDays'
          Id: S3BucketRule1
          Prefix: ''
          Status: Enabled
          Transitions:
          - StorageClass: STANDARD_IA
            TransitionInDays: !Ref 'IaInDays'
    Type: AWS::S3::Bucket
  BucketPolicy:
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument:
        Statement:
        - Action: s3:GetBucketAcl
          Effect: Allow
          Principal:
            Service: !If [ChinaRegionCondition, !Sub 'logs.${AWS::Region}.amazonaws.com.cn',
              !Sub 'logs.${AWS::Region}.amazonaws.com']
          Resource: !GetAtt 'Bucket.Arn'
        - Action: s3:PutObject
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
          Effect: Allow
          Principal:
            Service: !If [ChinaRegionCondition, !Sub 'logs.${AWS::Region}.amazonaws.com.cn',
              !Sub 'logs.${AWS::Region}.amazonaws.com']
          Resource: !Sub '${Bucket.Arn}/*'
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
