AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  ChinaRegionCondition: !Equals [!Ref 'AWS::Region', cn-north-1]
  HasBucketName: !Not [!Equals [!Ref 'BucketName', '']]
Description: Loadbalancer log bucket
Mappings:
  ElbAccountId:
    ap-northeast-1:
      ID: '582318560864'
    ap-northeast-2:
      ID: '600734575887'
    ap-south-1:
      ID: '718504428378'
    ap-southeast-1:
      ID: '114774131450'
    ap-southeast-2:
      ID: '783225319266'
    ca-central-1:
      ID: '985666609251'
    cn-north-1:
      ID: '638102146993'
    eu-central-1:
      ID: 054676820928
    eu-west-1:
      ID: '156460612806'
    eu-west-2:
      ID: '652711504416'
    sa-east-1:
      ID: '507241528517'
    us-east-1:
      ID: '127311923021'
    us-east-2:
      ID: 033677994240
    us-gov-west-1:
      ID: 048591011584
    us-west-1:
      ID: 027434742980
    us-west-2:
      ID: '797873946194'
Outputs:
  BucketName:
    Description: S3 bucket
    Value: !Ref 'Bucket'
Parameters:
  BucketName:
    AllowedPattern: '[-\.a-z0-9]*'
    Default: ''
    Description: Bucket name
    Type: String
Resources:
  Bucket:
    Properties:
      BucketName: !If [HasBucketName, !Ref 'BucketName', !Ref 'AWS::NoValue']
    Type: AWS::S3::Bucket
  BucketPolicy:
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument:
        Id: '1'
        Statement:
        - Action:
          - s3:PutObject
          Effect: Allow
          Principal:
            AWS:
            - !FindInMap [ElbAccountId, !Ref 'AWS::Region', ID]
          Resource: !Sub ['arn:${PARTITION}:s3:::${BUCKET}/*', {BUCKET: !Ref 'Bucket',
              PARTITION: !If [ChinaRegionCondition, aws-cn, aws]}]
          Sid: '1'
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
