AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  HasBucketName: !Not [!Equals [!Ref 'BucketName', '']]
Description: S3 storage bucket
Outputs:
  BucketArn:
    Description: Amazon Resource Name the bucket
    Value: !GetAtt 'Bucket.Arn'
  BucketName:
    Description: Bucket name
    Value: !Ref 'Bucket'
  DomainName:
    Description: IPv4 DNS name of the bucket
    Value: !GetAtt 'Bucket.DomainName'
Parameters:
  BucketName:
    AllowedPattern: '[-\.a-z0-9]*'
    Default: ''
    Description: Bucket name
    Type: String
Resources:
  Bucket:
    Properties:
      BucketName: !If [HasBucketName, !Ref 'BucketName', !Ref 'AWS::NoValue']
    Type: AWS::S3::Bucket
