AWSTemplateFormatVersion: '2010-09-09'
Description: Static s3 site with custom domain name
Outputs:
  BucketArn:
    Description: S3 bucket arn
    Value: !GetAtt 'Bucket.Arn'
  BucketName:
    Description: S3 bucket
    Value: !Ref 'Bucket'
  DomainName:
    Description: S3 bucket
    Value: !GetAtt 'Bucket.DomainName'
Parameters:
  DomainName:
    Description: Domain name
    Type: String
  ErrorDocument:
    Default: error.html
    Description: The name of the error document for the website.
    Type: String
  HostedZoneName:
    Description: Hosted zone name
    Type: String
  IndexDocument:
    Default: index.html
    Description: The name of the index document for the website.
    Type: String
Resources:
  Bucket:
    Properties:
      BucketName: !Sub '${DomainName}.${HostedZoneName}'
      WebsiteConfiguration:
        ErrorDocument: !Ref 'ErrorDocument'
        IndexDocument: !Ref 'IndexDocument'
    Type: AWS::S3::Bucket
  BucketPolicy:
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
          - !Sub '${Bucket.Arn}/*'
          Sid: PublicReadGetObject
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
