AWSTemplateFormatVersion: '2010-09-09'
Description: Automaticlly recover EC2 instance failure.

Parameters:
  RecoveryInstance:
    Description: The EC2 instance ID to associate this alarm with.
    Type: AWS::EC2::Instance::Id
  EvaluationPeriods:
    Description: Time before
    Type: Number
    Default: 15
    MinValue: 1
    MaxValue: 30

Conditions:
  ChinaRegionCondition: !Equals [!Ref 'AWS::Region', cn-north-1]

Resources:
  RecoveryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Trigger a recovery when instance status check fails for 15 consecutive minutes.
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: '60'
      EvaluationPeriods: !Ref EvaluationPeriods
      ComparisonOperator: GreaterThanThreshold
      Threshold: '0'
      AlarmActions:
      - !Sub ["arn:${PARTITION}:automate:${AWS::Region}:ec2:recover",
              {PARTITION: !If [ChinaRegionCondition, aws-cn, aws]}]
      Dimensions:
      - Name: InstanceId
        Value:
          Ref: RecoveryInstance