AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  HasName: !Not [!Equals [!Ref 'LogGroupName', '']]
  NotExpire: !Equals [!Ref 'RetentionDays', -1]
Description: CloudWatch Logs log group
Outputs:
  LogGroupArn:
    Description: Arn of the log group.
    Value: !GetAtt 'LogGroup.Arn'
  LogGroupName:
    Description: Name of the log group.
    Value: !Ref 'LogGroup'
Parameters:
  LogGroupName:
    AllowedPattern: '[\.\-_/#A-Za-z0-9]*'
    Default: ''
    Description: Name of the Log Group
    MaxLength: 512
    Type: String
  RetentionDays:
    AllowedValues:
    - -1
    - 1
    - 3
    - 5
    - 7
    - 14
    - 30
    - 60
    - 90
    - 120
    - 150
    - 180
    - 365
    - 400
    - 545
    - 731
    - 1827
    - 3653
    Default: '-1'
    Description: The number of days log events are kept in CloudWatch Logs.
    Type: Number
Resources:
  LogGroup:
    Properties:
      LogGroupName: !If [HasName, !Ref 'LogGroupName', !Ref 'AWS::NoValue']
      RetentionInDays: !If [NotExpire, !Ref 'AWS::NoValue', !Ref 'RetentionDays']
    Type: AWS::Logs::LogGroup
