AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  AlarmEnabledCondition: !Equals [!Ref 'AlarmEnabled', 'true']
  AlarmTopicCondition: !Not [!Equals [!Ref 'AlarmTopic', '']]
  InsufficientDataTopicCondition: !Not [!Equals [!Ref 'InsufficientDataTopic', '']]
  OkTopicCondition: !Not [!Equals [!Ref 'OkTopic', '']]
Description: Metric and alarm
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: LogGroup Configuration
      Parameters:
      - LogGroupName
    - Label:
        default: Metric FilterConfiguration
      Parameters:
      - MetricFilterPattern
      - MetricName
      - MetricNamespace
      - MetricValue
    - Label:
        default: Alarm Configuration
      Parameters:
      - AlarmEnabled
      - AlarmComparisonOperator
      - AlarmStatistic
      - AlarmThreshold
      - AlarmPeriod
      - AlarmEvaluationPeriods
      - AlarmUnit
    - Label:
        default: Notification Configuration
      Parameters:
      - NotificationEnabled
      - AlarmTopic
      - OkTopic
      - InsufficientDataTopic
    ParameterLabels:
      AlarmComparisonOperator:
        default: Alarm Comparison Operator
      AlarmEnabled:
        default: Alarm Enabled
      AlarmEvaluationPeriods:
        default: Alarm Evaluation Periods
      AlarmPeriod:
        default: Alarm Period
      AlarmStatistic:
        default: Alarm Statistic
      AlarmThreshold:
        default: Alarm Threshold
      AlarmTopic:
        default: Alarm Topic
      AlarmUnit:
        default: Alarm Unit
      InsufficientDataTopic:
        default: Insufficient Data Topic
      LogGroupName:
        default: Log Group Name
      MetricFilterPattern:
        default: Metric Filter Pattern
      MetricName:
        default: Metric Name
      MetricNamespace:
        default: Metric Namespace
      MetricValue:
        default: Metric Value
      NotificationEnabled:
        default: Notification Enabled
      OkTopic:
        default: Ok Topic
Outputs:
  AlarmName:
    Condition: AlarmEnabledCondition
    Description: Alarm name
    Value: !Ref 'Alarm'
  MetricFilter:
    Description: Metric filter
    Value: !Ref 'MetricFilter'
Parameters:
  AlarmComparisonOperator:
    AllowedValues:
    - GreaterThanOrEqualToThreshold
    - GreaterThanThreshold
    - LessThanThreshold
    - LessThanOrEqualToThreshold
    Default: GreaterThanThreshold
    Description: The arithmetic operation to use when comparing the specified Statistic
      and Threshold.
    Type: String
  AlarmEnabled:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Whether enables the alarm.  Set to false deletes the alarm resource.
    Type: String
  AlarmEvaluationPeriods:
    Default: '1'
    Description: The number of periods over which data is compared to the specified
      threshold.
    MaxValue: 1440
    MinValue: 1
    Type: Number
  AlarmPeriod:
    AllowedValues:
    - '60'
    - '300'
    - '900'
    - '3600'
    - '86400'
    Default: '60'
    Description: The time over which the specified statistic is applied. You must
      specify a time in seconds that is also a multiple of 60.
    Type: String
  AlarmStatistic:
    AllowedValues:
    - SampleCount
    - Average
    - Sum
    - Minimum
    - Maximum
    Default: Average
    Description: The statistic to apply to the alarm's associated metric.
    Type: String
  AlarmThreshold:
    Default: '0.0'
    Description: The value against which the specified statistic is compared.
    Type: Number
  AlarmTopic:
    Default: ''
    Description: SNS topic ARN to notify when alarm translates to ALARM state from
      any other state
    Type: String
  AlarmUnit:
    AllowedValues:
    - Seconds
    - Microseconds
    - Milliseconds
    - Bytes
    - Kilobytes
    - Megabytes
    - Gigabytes
    - Terabytes
    - Bits
    - Kilobits
    - Megabits
    - Gigabits
    - Terabits
    - Percent
    - Count
    - Bytes/Second
    - Kilobytes/Second
    - Megabytes/Second
    - Gigabytes/Second
    - Terabytes/Second
    - Bits/Second
    - Kilobits/Second
    - Megabits/Second
    - Gigabits/Second
    - Terabits/Second
    - Count/Second
    - None
    Default: None
    Description: The unit for the alarm's associated metric.
    Type: String
  InsufficientDataTopic:
    Default: ''
    Description: SNS topic ARN to notify when alarm translates to INSUFFICIENT_DATA
      state from any other state
    Type: String
  LogGroupName:
    AllowedPattern: '[\.\-_/#A-Za-z0-9]*'
    Default: ''
    Description: Name of the Log Group
    MaxLength: 512
    Type: String
  MetricFilterPattern:
    Default: '[ERROR]'
    Description: Filter pattern of LogGroup metric filter.
    MaxLength: 1024
    MinLength: 0
    Type: String
  MetricName:
    AllowedPattern: '[^:*$]*'
    Default: Metric
    Description: The name of the CloudWatch metric.
    MaxLength: 255
    MinLength: 0
    Type: String
  MetricNamespace:
    AllowedPattern: '[^:*$]*'
    Default: Metrics
    Description: The namespace of the CloudWatch metric.
    MaxLength: 255
    MinLength: 0
    Type: String
  MetricValue:
    Default: '1'
    Description: The value to publish to the CloudWatch metric when a filter pattern
      matches a log event.
    MaxLength: 100
    MinLength: 0
    Type: String
  NotificationEnabled:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Description: whether actions should be executed during any changes to the alarm's
      state.
    Type: String
  OkTopic:
    Default: ''
    Description: SNS topic ARN to notify when alarm translates to OK state from any
      other state
    Type: String
  TreatMissingData:
    AllowedValues:
    - breaching
    - notBreaching
    - ignore
    - missing
    Default: missing
    Description: Specifies how the alarm treats missing data points.
    Type: String
Resources:
  Alarm:
    Condition: AlarmEnabledCondition
    Properties:
      ActionsEnabled: !Ref 'NotificationEnabled'
      AlarmActions:
      - !If [AlarmTopicCondition, !Ref 'AlarmTopic', !Ref 'AWS::NoValue']
      ComparisonOperator: !Ref 'AlarmComparisonOperator'
      EvaluationPeriods: !Ref 'AlarmEvaluationPeriods'
      InsufficientDataActions:
      - !If [InsufficientDataTopicCondition, !Ref 'InsufficientDataTopic', !Ref 'AWS::NoValue']
      MetricName: !Ref 'MetricName'
      Namespace: !Ref 'MetricNamespace'
      OKActions:
      - !If [OkTopicCondition, !Ref 'OkTopic', !Ref 'AWS::NoValue']
      Period: !Ref 'AlarmPeriod'
      Statistic: !Ref 'AlarmStatistic'
      Threshold: !Ref 'AlarmThreshold'
      TreatMissingData: !Ref 'TreatMissingData'
      Unit: !Ref 'AlarmUnit'
    Type: AWS::CloudWatch::Alarm
  MetricFilter:
    Properties:
      FilterPattern: !Ref 'MetricFilterPattern'
      LogGroupName: !Ref 'LogGroupName'
      MetricTransformations:
      - MetricName: !Ref 'MetricName'
        MetricNamespace: !Ref 'MetricNamespace'
        MetricValue: !Ref 'MetricValue'
    Type: AWS::Logs::MetricFilter
