AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  FiveEmailsCondition: !Or
    - !Equals
      - !Ref 'NumOfEmails'
      - '6'
    - !Equals
      - !Ref 'NumOfEmails'
      - '5'
  FourEmailsCondition: !Or
    - !Equals
      - !Ref 'NumOfEmails'
      - '6'
    - !Equals
      - !Ref 'NumOfEmails'
      - '5'
    - !Equals
      - !Ref 'NumOfEmails'
      - '4'
  HasDisplayNameCondition: !Not
    - !Equals
      - !Ref 'DisplayName'
      - ''
  SixEmailsCondition: !Equals
    - !Ref 'NumOfEmails'
    - '6'
  ThreeEmailsCondition: !Or
    - !Equals
      - !Ref 'NumOfEmails'
      - '6'
    - !Equals
      - !Ref 'NumOfEmails'
      - '5'
    - !Equals
      - !Ref 'NumOfEmails'
      - '4'
    - !Equals
      - !Ref 'NumOfEmails'
      - '3'
  TwoEmailsCondition: !Or
    - !Equals
      - !Ref 'NumOfEmails'
      - '6'
    - !Equals
      - !Ref 'NumOfEmails'
      - '5'
    - !Equals
      - !Ref 'NumOfEmails'
      - '4'
    - !Equals
      - !Ref 'NumOfEmails'
      - '3'
    - !Equals
      - !Ref 'NumOfEmails'
      - '2'
Description: Alarm with email notification
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Alarm Configuration
        Parameters:
          - AlarmEmails
          - NumOfEmails
    ParameterLabels:
      AlarmEmails:
        default: Alarm Emails
      NumOfEmails:
        default: Num Of Emails
Outputs:
  TopicArn:
    Description: Topic arn
    Export:
      Name: !Sub '${AWS::StackName}-TopicArn'
    Value: !Ref 'AlarmTopic'
  TopicName:
    Description: Topic name
    Export:
      Name: !Sub '${AWS::StackName}-TopicName'
    Value: !GetAtt 'AlarmTopic.TopicName'
Parameters:
  AlarmEmails:
    Default: nobody@amazon.com
    Description: List of comma delimited email address to notify.
    Type: CommaDelimitedList
  DisplayName:
    Default: ''
    Description: User defined string that can be used to identify this SNS topic.
    Type: String
  NumOfEmails:
    AllowedValues:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
    Default: '1'
    Description: Number of email addresses in AlarmEmails.
    Type: String
Resources:
  AlarmTopic:
    Properties:
      DisplayName: !If
        - HasDisplayNameCondition
        - !Ref 'DisplayName'
        - !Ref 'AWS::NoValue'
      Subscription:
        - Endpoint: !Select
            - 0
            - !Ref 'AlarmEmails'
          Protocol: email
        - !If
          - TwoEmailsCondition
          - Endpoint: !Select
              - 1
              - !Ref 'AlarmEmails'
            Protocol: email
          - !Ref 'AWS::NoValue'
        - !If
          - ThreeEmailsCondition
          - Endpoint: !Select
              - 2
              - !Ref 'AlarmEmails'
            Protocol: email
          - !Ref 'AWS::NoValue'
        - !If
          - FourEmailsCondition
          - Endpoint: !Select
              - 3
              - !Ref 'AlarmEmails'
            Protocol: email
          - !Ref 'AWS::NoValue'
        - !If
          - FiveEmailsCondition
          - Endpoint: !Select
              - 4
              - !Ref 'AlarmEmails'
            Protocol: email
          - !Ref 'AWS::NoValue'
        - !If
          - SixEmailsCondition
          - Endpoint: !Select
              - 5
              - !Ref 'AlarmEmails'
            Protocol: email
          - !Ref 'AWS::NoValue'
    Type: AWS::SNS::Topic
