AWSTemplateFormatVersion: '2010-09-09'
Description: Dns alias record to a specific ip
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Dns Configuration
      Parameters:
      - HostedZoneName
      - DomainName
      - RecordTypeTarget
      - Ttl
    ParameterLabels:
      DomainName:
        default: Domain Name
      HostedZoneName:
        default: Hosted Zone Name
      RecordTypeTarget:
        default: Record Type Target
      Ttl:
        default: Ttl
Outputs:
  DnsName:
    Description: DNS name
    Export:
      Name: !Sub '${AWS::StackName}-DnsName'
    Value: !Ref 'Record'
Parameters:
  DomainName:
    Description: Domain name
    Type: String
  HostedZoneName:
    Description: Hosted zone name
    Type: String
  RecordType:
    AllowedValues:
    - A
    - CNAME
    Default: A
    Description: Dns record type
    Type: String
  Target:
    Description: Alias/cname target
    Type: String
  Ttl:
    Default: '300'
    Description: DNS time to live
    MaxValue: '86400'
    MinValue: '1'
    Type: Number
Resources:
  Record:
    Properties:
      HostedZoneName: !Sub '${HostedZoneName}.'
      Name: !Sub '${DomainName}.${HostedZoneName}'
      ResourceRecords:
      - !Ref 'Target'
      TTL: !Ref 'Ttl'
      Type: !Ref 'RecordType'
    Type: AWS::Route53::RecordSet
