AWSTemplateFormatVersion: "2010-09-09"
Description: "Weighted dns records"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Domain Name Configuration
      Parameters:
        - DomainName
        - HostZoneName
    - Label:
        default: Resource A Configuration
      Parameters:
        - ResourceDomainNameA
        - ResourceIdentifierA
        - ResourceWeightA
        - TTLA
    - Label:
        default: Resource B Configuration
      Parameters:
        - ResourceDomainNameB
        - ResourceIdentifierB
        - ResourceWeightB
        - TTLB
    ParameterLabels:
      DomainName:
        default: Host Domain Name
      HostZoneName:
        default: Host Zone Name
      ResourceDomainNameA:
        default: Domain Name
      ResourceIdentifierA:
        default: Identifier
      ResourceWeightA:
        default: Weight
      TTLA:
        default: TTL
      ResourceDomainNameB:
        default: Domain Name
      ResourceIdentifierB:
        default: Identifier
      ResourceWeightB:
        default: Weight
      TTLB:
        default: TTL
Parameters:
  DomainName:
    Description: "The domain name of the host."
    Type: String
  HostZoneName:
    Description: "Hosted zone name."
    Type: String
  ResourceDomainNameA:
    Description: "The domain name of resource A."
    Type: String
  ResourceIdentifierA:
    Description: "The unique id of resource A."
    Type: String
    Default: "A"
  ResourceWeightA:
    Description: "The weight of resource A."
    Type: Number
    Default: 50
  ResourceDomainNameB:
    Description: "The domain name of resource B."
    Type: String
  ResourceIdentifierB:
    Description: "The unique id of resource B."
    Type: String
    Default: "B"
  ResourceWeightB:
    Description: "The weight of resource B."
    Type: Number
    Default: 50
  TTLA:
    Description: "The resource A record cache time to live (TTL), in seconds."
    Type: Number
    Default: 300
    MaxValue: 86400
    MinValue: 1
  TTLB:
    Description: "The resource B record cache time to live (TTL), in seconds."
    Type: Number
    Default: 300
    MaxValue: 86400
    MinValue: 1
Resources:
  DnsRecordA:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName:
        Fn::Sub: "${HostZoneName}."
      Name:
        Fn::Sub: "${DomainName}.${HostZoneName}"
      Type: CNAME
      SetIdentifier:
        Ref: ResourceIdentifierA
      ResourceRecords:
        - Ref: ResourceDomainNameA
      Weight:
        Ref: ResourceWeightA
      TTL:
        Ref: TTLA
  DnsRecordB:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName:
        Fn::Sub: "${HostZoneName}."
      Name:
        Fn::Sub: "${DomainName}.${HostZoneName}"
      Type: CNAME
      SetIdentifier:
        Ref: ResourceIdentifierB
      ResourceRecords:
        - Ref: ResourceDomainNameB
      Weight:
        Ref: ResourceWeightB
      TTL:
        Ref: TTLB
Outputs:
  DnsName:
    Description: DNS name
    Value:
      Ref: DnsRecordA
